name: Certificaciones Backend Produccion

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: accesa-desarrollo
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the certificaciones_back_prod Docker image
      run: |
       docker build . --tag ghcr.io/accesa-desarrollo/certificaciones_back_prod:latest
       docker push ghcr.io/accesa-desarrollo/certificaciones_back_prod:latest

  